
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia
    username: postgres
    password: postgres
  jpa:
    show-sql: true        # vai mostrar no log o sql.
    hibernate:
      ddl-auto: update
